---
- hosts: all
  become: true
  tasks:
    - name: .deb dist-upgrade
      apt: >
        update_cache=yes
        cache_valid_time=1200
        upgrade=dist
        autoclean=yes
        autoremove=yes
        force_apt_get=yes
      when: >
        ansible_distribution == 'Debian' and ansible_distribution_version is version_compare('8', '>=')
        or
        ansible_distribution == 'Ubuntu'
